dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - PREMAKE_CC=gcc
    - os: linux
      compiler: clang
      env:
        - PREMAKE_CC=clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgl1-mesa-dev libgtk-3-dev xorg-dev

install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
  - tar -xf premake.tar.gz
  - ./premake5 --cc=$PREMAKE_CC gmake
  - cd build/gmake_$PREMAKE_CC

script:
  make
